version: '3'

services:
  app:
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--enable-source-maps
    ports:
      - 9222:9222
    volumes:
      - ./dist:/usr/src/app/dist
      - ./package.json:/usr/src/app/package.json
      - ./forever.json:/usr/src/app/forever.json
      - ./yarn.lock:/usr/src/app/yarn.lock
      - ./assets:/usr/src/app/assets
      - ./types:/usr/src/app/types
    command: yarn watch-js