version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - 80:3000
    env_file:
      - .env
    networks:
      - default
    # volumes:
    #   - tdlib-db:/usr/src/app/tdl-db
    #   - tdlib-files:/usr/src/app/tdl-files
    command: yarn start

# volumes:
#   tdlib-db:
#   tdlib-files:

networks:
  default:
    driver: bridge