version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    command: yarn start
    volumes:
      - app-data:/usr/src/app/
    networks:
      - default
    depends_on:
      - tdlib
  tdlib:
    build: deploy/tdlib
    volumes:
      - app-data:/usr/local/lib/

volumes:
  app-data:

networks:
  default:
    driver: bridge