version: '3'

services:
  trashtaste-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    command: yarn start
    volumes:
      - .:/usr/src/app
    networks:
      - default

networks:
  default:
    driver: bridge