services:
  app:
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--enable-source-maps
    ports:
      - 9229:9229
    volumes:
      - ./package.json:/app/package.json
      - ./nodemon.json:/app/nodemon.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./assets:/app/assets
      - ./types:/app/types
      - ./src:/app/src
    command: pnpm dev